### ISSUE TITLE
The tab key does not indent template text

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#29] opened 2020-04-17 20:01 UTC
If you select a few lines of text _outside_ of `<#`...`#>` regions and press tab, the selected text gets replaced with a tab instead of being indented. Shift+Tab unindents the text as expected.

The tab key works as expected inside `<#`...`#>` blocks.

**Comment by ltrzesniewski** [comment] 2020-04-20 10:18
This may be related to https://youtrack.jetbrains.com/issue/RSRP-474524

**Comment by kirillgla** [comment] 2020-04-20 12:00
Thank you. The problem you reported is indeed a duplicate of [that one](https://youtrack.jetbrains.com/issue/RSRP-474524). Feel free to follow it for updates 😄

**Closed by kirillgla** 2020-04-20 12:00 UTC
